feat(subscription-service): add billing functionality to subscription…
sourcefuse/arc-saas pull request #38
Opened 2024-08-05 14:56 UTC by Tyagi-Sunny

add billing functionality to subscription service

BREAKING CHANGE:
yes

gh-34

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2024-09-17 07:58 UTC, a-ganguly approved these changes
Add billing functionality to subscription

2024-09-17 11:55 UTC, rohit-sourcefuse approved these changes

2024-12-13 08:06 UTC, yeshamavani requested changes

2024-12-13 08:06 UTC, yeshamavani commented on services/subscription-service/.gitignore
please revert this

2024-12-13 08:06 UTC, yeshamavani commented on services/subscription-service/src/models/dto/customer-dto.model.ts
> +}
why is this needed

2024-12-13 08:28 UTC, Tyagi-Sunny commented on services/subscription-service/.gitignore
done

2024-12-13 08:28 UTC, Tyagi-Sunny commented on services/subscription-service/src/models/dto/customer-dto.model.ts
> +}
removed

2024-12-13 09:29 UTC, merged