feat(tenant-management):integrate auth0
sourcefuse/arc-saas pull request #48
Opened 2024-09-27 09:22 UTC by Surbhi-sharma1

## Description

integrate auth0 in tenant management service
Fixes #47 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2024-09-27 10:47 UTC, yeshamavani commented on services/tenant-management-service/migrations/pg/migrations/sqls/20240925102459-add-table-tenant-configs-up.sql
add the trigger to update the modified_on time whenever there is an update

2024-09-27 10:47 UTC, yeshamavani commented on services/tenant-management-service/src/models/dtos/tenant-dto.model.ts
> +
plans will be separate not a part of tenant

2024-09-27 10:47 UTC, yeshamavani commented on services/tenant-management-service/src/models/tenant-config.model.ts
> +
why is the configValue type defined like this 
it not specific to just auth0 and organizations 
its a generic table that can be used for anything in future
its just a json value https://github.com/sourcefuse/loopback4-microservice-catalog/blob/master/services/authentication-service/src/models/tenant-config.model.ts

2024-09-27 10:47 UTC, yeshamavani commented on services/tenant-management-service/src/types/i-idp.interface.ts
> +export type ConfigureIdpFunc<T> = (payload: IdpDetails) => Promise<T>;
name of this type

2024-09-27 10:50 UTC, yeshamavani requested changes

2024-09-27 10:50 UTC, yeshamavani commented on services/tenant-management-service/src/providers/idp/idp-auth0.provider.ts
> +    const organizationData: OrganizationData = {
tenant_config depends on two things 
tenant_id and config_key 
please take key also into account as I can store diff types of config for a tenant

2024-09-27 10:50 UTC, yeshamavani commented on services/tenant-management-service/src/providers/idp/types.ts
why userdata and organizationdata types defined 
arent these defined in the auth0 management package

2024-09-27 10:52 UTC, yeshamavani commented
Also is this https://github.com/sourcefuse/arc-saas/pull/38 PR included in this new PR ??
@Surbhi-sharma1 @Tyagi-Sunny

2024-09-30 05:55 UTC, Surbhi-sharma1 commented
https://github.com/sourcefuse/arc-saas/pull/51
closing as raised above PR

2024-09-30 05:56 UTC, closed without merging