Gh 47
sourcefuse/arc-saas pull request #53
Opened 2024-10-07 05:28 UTC by Tyagi-Sunny

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2024-10-07 05:40 UTC, Tyagi-Sunny commented on services/tenant-management-service/src/component.ts
> +      IdpController,
remove this IdpController from service component

2024-10-07 05:45 UTC, Tyagi-Sunny commented on services/tenant-management-service/src/models/dtos/idp-details-dto.model.ts
> +  tenant: AnyObject;
why are we giving tenant as AnyObject

2024-10-07 05:47 UTC, Tyagi-Sunny commented on services/tenant-management-service/src/models/dtos/tenant-dto.model.ts
> +export class TenantDto extends Tenant {
made changes to TenantDto and set this as type of tenant in IdpDetailsDto

2024-10-07 05:50 UTC, Tyagi-Sunny commented on services/tenant-management-service/src/providers/idp/types.ts
> +export type Auth0Response = {
as we are using a commong resp IdpResp={authId:string}, we can remove this Auth)response

2024-10-07 05:52 UTC, Tyagi-Sunny commented on services/tenant-management-service/src/webhook.component.ts
> +      TenantConfigTenantController,
remove tenantConfigController and tenantconfigtenat controller from here. only idp controller should be her

2024-10-07 07:25 UTC, Tyagi-Sunny commented on services/tenant-management-service/src/component.ts
> +      IdpController,
done

2024-10-17 06:59 UTC, yeshamavani requested changes

2024-10-17 06:59 UTC, yeshamavani commented on services/tenant-management-service/src/models/dtos/tenant-dto.model.ts
> +export class TenantDto extends Tenant {
I have done that changes on the fly as few of the properties like address.state, leadId were all null and type for that was given as string

This was done just for testing 
make sure to change the types later

2024-10-17 06:59 UTC, yeshamavani commented on services/tenant-management-service/src/providers/idp/idp-auth0.provider.ts
> +        'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*()_+~`|}{[]:;?><,./-=';
use regex @Surbhi-sharma1

2024-10-17 11:47 UTC, Surbhi-sharma1 commented on services/tenant-management-service/src/providers/idp/idp-auth0.provider.ts
> +        'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*()_+~`|}{[]:;?><,./-=';
Done

2024-12-13 13:28 UTC, merged